### ISSUE TITLE
Fix tests and CI

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-interface#201]
Netifly

![Screenshot at 2021-06-07 13-00-06.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/7013eeb3-ca23-4a3a-ab72-1bf4661176ca)

**Comment by rossneilson** [comment]
#202 Merged to dev in order to run CI build on dev branch PRs

**Netlify checks:**
Not entirely sure if these are required for every PR (seems they are not).
Since I don't have direct access I don't know exactly how these are configured. But, from past netlify experience, the below should work.
If this is the case it can be disabled via: Settings -> Build and deploy -> Continious deployment -> Deploy contexts -> Deploy previews
![Netlify settings](https://user-images.githubusercontent.com/39137239/121010615-8c1da000-c78d-11eb-8722-b31227e6e7a0.png)

**Comment by martinkrung** [comment]
@rossneilson 

I did see this github action error, but may be becuase of warnings? I yes, just close this ticket again.

![Screenshot at 2021-06-09 17-19-12.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/04c1c4a0-ba0f-4f0a-99e8-8f5f1acc0b1d)

![Screenshot at 2021-06-09 17-24-14.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/bab6b911-0cc8-4d16-82f1-0c3922ca3ca0)


![Screenshot at 2021-06-09 17-22-09.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/83da1942-fbb5-4c8d-8646-6329a8c1d095)

**Comment by rossneilson** [comment]
> @rossneilson
> 
> I did see this github action error, but may be because of warnings? I yes, just close this ticket again. Happening here: #225
> 
> ![Screenshot at 2021-06-09 17-19-12.png](https://camo.githubusercontent.com/4a6a2702b7bdffcc9ad54763e4f31099d04b5e24b43ab7d405ea88d80a02a700/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630623462313636373463643333633663376334393532632f30346331633461302d626130662d346630612d393965382d386635663161636330623164)
> 
> ![Screenshot at 2021-06-09 17-24-14.png](https://camo.githubusercontent.com/11d405e756d18e64e205e6b744c39e4e79d5c6c937964a3271545c1cfed33a74/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630623462313636373463643333633663376334393532632f62616236623931312d306363382d346431362d383266312d306333393232636133636130)
> 
> ![Screenshot at 2021-06-09 17-22-09.png](https://camo.githubusercontent.com/869c1eb895f8f27ba1c15c0dfa24b27c566af16bfb3600fff30b040dcbf606cb/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630623462313636373463643333633663376334393532632f38336461313934322d666262352d346338642d383634362d363332396138633164303935)

Yeah, we can add a rule to ignore these kinds of errors but probably best to fix them
