### ISSUE TITLE
Amounts are denominated in tokenIn rather than TokenOut in PurchaseBidForm

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#271]
## Description
Form field input is being denominated in the input token rather than the amount being denominated in the Output token. [more info can be seen here](https://github.com/cryptonative-ch/mesa-interface/pull/268#discussion_r654284464)

## Expected Behavior
* Form input field should be denominated in tokenOut rather than in tokenIn

## Actual Behavior
* Form input field is denominated in tokenIn rather than in tokenOut

## Possible Fix
* UP TO THE DEVELOPER

## Context
It confuses the user.

**Comment by rossneilson** [comment]
The denomination of the form in tokensIn was a request by @martinkrung https://github.com/cryptonative-ch/mesa-interface/issues/241.

The amount sent to the smart contract is denominated in tokensOut as it should be according to SC.

![2021-06-21 17.23.45.png](https://images.zenhubusercontent.com/60b4ff93c021492a4067ae98/c4cb7ba2-1cdb-4aa8-af9c-b6cf42fda7aa)
![image.png](https://images.zenhubusercontent.com/60b4ff93c021492a4067ae98/85f89b3a-3ca3-406a-a35a-66411d344b24)
![2021-06-21 17.50.40.png](https://images.zenhubusercontent.com/60b4ff93c021492a4067ae98/ab5b92d9-6534-4313-9f7f-e2ce1abd1320)

---

However I do think I have found an issue with SC cleanup branch:

Currently in smart contract(SC) `main` branch amount and by extension `tokensPurchased` is denominated in tokensOut.
However there is a known bug where when releasing or claiming the amount is simply sent out of tokensPurchases regardless of whether it should be tokensIn or tokensOut.

The solution should be to change the total calculation on `releaseTokens()`. 
However in cleanup branch the change was made to `claimTokens`. 
Essentially this means that the new code treats `tokensPurchased` as denominated in `tokensIn` when it should be `tokensOut`.

If this is intentional it will require a lot of changes in the UI and SC.

I dont think the error is with the UI but with the current known bug in main and the solution in cleanup.
I have made a comment on the cleanup PR draft.
