### ISSUE TITLE
Scroll Bar should fit with Aqua theme

### ISSUE THREAD

**Issue by hhamud** [cryptonative-ch/mesa-interface#310]
## Detailed Description
- Scroll bar should disappear when it is not in use or if the height of the `SelfBidList` component is too low. 
- Scroll bar aesthetic should be in line with the theme of the application.

**Comment by martinkrung** [comment]
I think we should not use a scroll bar at all. It's just unnecessary. 

The reason: If you duplicate standard interaction, normal scrolling always wins. It's unnecessary clutter. 

Why not make that window just as high that everything fits?  Most user will have 1-3 entry in this list on a fixed price sale, on a auction maybe more, but the average user will not make 10 bids.

And I have done a few costume "Scroll bar"  in my past life. It's a pain, because you are replacing a standard UX pattern.
