### ISSUE TITLE
Incorrect display of dates

### ISSUE THREAD

**Issue by mprasanjith** [cryptonative-ch/mesa-interface#424]
The UI does not show the year when showing dates.

![image.png](https://images.zenhubusercontent.com/60bdf8f2726f4149933d9543/92e8a88e-e67f-4f88-8183-ccfd6fbecf5c)

In this scenario, the actual date is Aug 29. 2018, while the UI just shows Aug 29. The same issue is present in sale cards as well.

This issue can be reproduced by using the subgraph mocks.

Potential solution would be to optionally show the year only for years other than the current. We can also use something like `formatDistance` or `formatRelative` of data-fns library to have much more human-readable dates.

PS: [`formatDistanceToNowStrict`](https://date-fns.org/v2.23.0/docs/formatDistanceToNowStrict) is exactly what we need, although I'm not sure if we should use date-fns as well as we have dayjs in our code.

**Comment by hhamud** [comment]
It wasn't included in the [figma designs](https://www.figma.com/file/7vH0nZB72tizFbhT7gtizo/Mesa-MVP?node-id=408%3A170) originally. I'm not familiar with the `data-fns` library. If we only need a single function from that library can we not just write the function using dayjs ourselves?. I raise this because as you have said before in #409 the bundle size is quite large.

**Comment by mprasanjith** [comment]
Yeah I agree we should definitely use dayjs. I didn't quite realize we have it in our codebase when I added the original description. Introducing human readable dates is an additional thing anyway, but we should show the year to the user, or its very misleading.
